### PR TITLE
Pod ingress network shaping Chaos scenario

### PR DESCRIPTION
**Pull request by yogananth-subramanian**
The scenario introduces network latency, packet loss, and bandwidth restriction in the Pod's network interface. The purpose of this scenario is to observe faults caused by random variations in the network.

Below example config applies ingress traffic shaping to openshift console.
````
- id: pod_ingress_shaping
  config:
    namespace: openshift-console   # Required - Namespace of the pod to which filter need to be applied.
    label_selector: 'component=ui' # Applies traffic shaping to access openshift console.
    network_params:
        latency: 500ms             # Add 500ms latency to ingress traffic from the pod.
````

### CODE REVIEW

**Comment by paigerube14** [comment]
Can you update a scenario file for this scenario type? Or is one of the existing scenario files similar that it should be edited?

**Comment by yogananth-subramanian** [comment]
> Can you update a scenario file for this scenario type? Or is one of the existing scenario files similar that it should be edited?

Hello Paige, thought we could reuse the existing scenario file related to [pod_network_shaping ](scenarios/openshift/pod_network_shaping.yml ), since the variables for the current scenario(ingress) and existing one,egress, are the same. But have update the [doc](docs/pod_network_scenarios.md), which should help the user pick and populate the right variables.

**Comment by paigerube14** [comment]
@yogananth-subramanian gotcha, I just wasn't sure which one was most similar. Sounds good!

**Comment by yogananth-subramanian** [comment]
> @yogananth-subramanian gotcha, I just wasn't sure which one was most similar. Sounds good!

Or let me create a new scenario file for this patch and rename the  [pod_network_shaping](https://github.com/redhat-chaos/krkn/pull/scenarios/openshift/pod_network_shaping.yml) to pod_egress_shaping

**Comment by paigerube14** [comment]
Once we update the conflicts I think everything looks good to merge

**Review by chaitanyaenr — APPROVED** [review]
LGTM!

**Review by chaitanyaenr — APPROVED** [review]

**Pull request merged**
